# CHAOS Agent Registry v2.0
#
# This file provides centralized discovery of all agents.
# The orchestrator reads this to understand available agents without loading full definitions.
#
# Schema version: 2.0.0
# Framework version: 0.3.0

metadata:
  schema_version: "2.0.0"
  framework_version: "0.3.0"
  last_updated: "2025-02-03"

# Model Selection Guide
#
# haiku  - Fast, cheap ($0.25/1M input). Use for: exploration, verification, simple tasks
# sonnet - Balanced ($3/1M input). Use for: planning, reviewing, complex reasoning
# opus   - Most capable ($15/1M input). Use for: implementation, complex code generation
#
# Thinking Triggers (in order of intensity):
#   "think"       - Light deliberation (haiku tasks)
#   "think hard"  - Moderate analysis (sonnet tasks, implementation)
#   "think harder"- Deep reasoning (planning, dispute resolution)
#   "ultrathink"  - Maximum deliberation (spec creation, architecture)

# Pipeline Agents (ordered by typical execution)
pipeline:
  spec-reviewer:
    version: "1.0.0"
    description: Validates spec completeness, asks clarifying questions
    model: sonnet
    phase: review
    thinking_trigger: null  # Uses structured checklist instead
    tools: [Read, Grep, Glob, AskUserQuestion]
    returns: "status, completeness score, questions, ready (yes/no)"
    estimated_tokens: 5000-15000

  spec-architect:
    version: "1.0.0"
    description: Transforms intent/analysis into well-formed specifications
    model: opus
    phase: spec-creation
    thinking_trigger: ultrathink
    tools: [Read, Grep, Glob, Bash, Write, AskUserQuestion]
    returns: "spec location, files created, requirements count, decisions documented"
    estimated_tokens: 15000-40000

  explore:
    version: "1.0.0"
    description: Fast codebase investigation to find patterns and relevant files
    model: haiku
    phase: explore
    thinking_trigger: null  # Speed-focused
    tools: [Read, Grep, Glob]
    returns: "key files, patterns found, guidance for plan"
    estimated_tokens: 3000-10000

  scout:
    version: "1.0.0"
    description: Deep codebase exploration for spec creation context
    model: haiku
    phase: spec-creation
    thinking_trigger: think
    tools: [Read, Grep, Glob, Bash]
    returns: "similar implementations, patterns, files to modify, conflicts"
    estimated_tokens: 5000-15000

  code-explorer:
    version: "1.0.0"
    description: Systematic codebase health analysis for tech debt, test gaps, security issues
    model: haiku
    phase: analysis
    thinking_trigger: null  # Systematic scanning
    tools: [Read, Grep, Glob, Bash]
    returns: "health summary, prioritized findings by category and severity"
    estimated_tokens: 10000-30000

  plan:
    version: "1.0.0"
    description: Designs implementation approach based on exploration
    model: sonnet
    phase: plan
    thinking_trigger: think_harder
    tools: [Read, Grep, Glob, Bash]
    returns: "files to modify, approach, testing strategy"
    estimated_tokens: 8000-20000

  implement:
    version: "1.0.0"
    description: Writes code following the plan
    model: opus
    phase: implement
    thinking_trigger: think_hard
    tools: [Read, Write, Edit, Bash, Grep, Glob]
    standards: [global/*, backend/*, frontend/*]
    returns: "files changed, tests added, verification status"
    estimated_tokens: 20000-80000

  verifier:
    version: "1.0.0"
    description: Quick verification that acceptance criteria are met
    model: haiku
    phase: verify
    thinking_trigger: null  # Binary pass/fail
    tools: [Read, Grep, Glob, Bash]
    returns: "verdict (PASS/FAIL), criteria met, test status"
    estimated_tokens: 3000-8000

  code-reviewer:
    version: "1.0.0"
    description: Strict quality gate for code changes
    model: sonnet
    phase: review
    thinking_trigger: think_hard
    tools: [Read, Grep, Glob, Bash]
    standards: [global/*, testing/*]
    returns: "verdict (APPROVED/CHANGES_REQUESTED), issues, feedback"
    estimated_tokens: 5000-15000

  dispute-resolver:
    version: "1.0.0"
    description: Decides retry strategy or escalation after failures
    model: sonnet
    phase: escalation
    thinking_trigger: think_harder
    tools: [Read, AskUserQuestion]
    returns: "decision (RETRY/ESCALATE), guidance"
    estimated_tokens: 3000-8000

# Support Agents
support:
  tooling-setup:
    version: "1.0.0"
    description: Diagnoses and repairs tooling issues from preflight failures
    model: haiku
    thinking_trigger: null
    tools: [Bash, Read, Write]
    returns: "status (READY/BLOCKED), fixes applied, manual actions needed"
    estimated_tokens: 2000-5000

  beads-helper:
    version: "1.0.0"
    description: Executes beads commands for issue management
    model: haiku
    thinking_trigger: null
    tools: [Bash]
    returns: "operations performed, issue IDs, sync status"
    estimated_tokens: 1000-3000

# Phase Ordering
phases:
  - spec-creation: [scout, spec-architect]
  - review: [spec-reviewer, code-reviewer]
  - explore: [explore, code-explorer]
  - plan: [plan]
  - implement: [implement]
  - verify: [verifier]
  - escalation: [dispute-resolver]
